#!/bin/bash

###################################################################
# Author: Bade
# Purpose: Script for backing database on Posgresql
# Date Updated: 09/08/2020
###################################################################

# $1 specify the database name while running the script 
# eg if you name the script as pg_backup.sh then run './pg_backup.sh dbname' 
# if the db_name is testdb then run './pg_backup.sh testdb'

# specify Backup name, path and suffix
DB_NAME=$1
BACKUP_DIR=/var/lib/pgsql/backups
FILE_SUFFIX=_${DB_NAME}_backup.tar

# Name file using the date, time and supplied suffix
FILE=`date +"%Y-%m-%d-%H%M"`${FILE_SUFFIX}

# Combine the backup directory and file name
OUTPUT_FILE=${BACKUP_DIR}/${FILE}

# Execute the backup as a tar
pg_dump -F t $1 > ${OUTPUT_FILE}
